# This file was generated by GoReleaser. DO NOT EDIT.
cask "bmor" do
  version "0.1.0-rc.10"

  on_macos do
    on_intel do
      sha256 "2ea6e63676d3359cce942141f27db75fd2132f964b7452c3869c526d35368ae7"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c33278c8f2d6aa958ee405d97af2204b19b68571904922e814b4fb9029582cb"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3df3f6f99ad243c47462b5adf143e72a81a32e1b68b1daf3fe758be5abfd7df"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee5e62435e7c8ef30ddc071b00292aace5fa05429c8dc8931cc2d2040e9bd94c"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bmor"
  desc "AI coding assistant usage collector for Branchmore"
  homepage "https://github.com/branchmore/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bmor"

  # No zap stanza required

end
