# This file was generated by GoReleaser. DO NOT EDIT.
cask "bmor" do
  version "0.1.0-rc.8"

  on_macos do
    on_intel do
      sha256 "3c3c382ea6c2cfb7cc61359a8984dded1f85bae4fa1671d5ff1e22d02e34c85c"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ceeafb16463b9983ab25ca4c49c826c664c3bfc1353ce0c326ff9eb3064b3b99"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d18c67fb629101c8e2e9596c40b33e6f4e8f45f5eba2001114400dde710b85af"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "50058f3fe84b2ac6e46bcd4fc252852e7eb9ca43d4b5f18451c58853683d7e36"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bmor"
  desc "AI coding assistant usage collector for Branchmore"
  homepage "https://github.com/branchmore/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bmor"

  # No zap stanza required

end
