# This file was generated by GoReleaser. DO NOT EDIT.
cask "bmor" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "1b6a039aef17acc36b8457250417841b1abc176ecdcf8c00b3a8da8e3b288b64"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "943acf764dab6f8e5e044c6e683ddffc276cea19f08061c1f1c674bbb1535c94"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3fad27c6a5de76dade2a7f3bca91002652fa1c1603420c1451eae2510a506bcd"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d42a719cb32b4ce6c5a46eb4316693c26b68f05b430085b4238df57bc2ee4a3"
      url "https://github.com/branchmore/cli/releases/download/v#{version}/bmor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bmor"
  desc "AI coding assistant usage collector for Branchmore"
  homepage "https://github.com/branchmore/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bmor"

  # No zap stanza required

end
